import { PrismaClient, Category } from "../src/generated/prisma/client";

const prisma = new PrismaClient();

function photo(slug: string, index: number, caption: string, isCover = false) {
  return {
    url: `https://picsum.photos/seed/${slug}-${index}/800/600`,
    caption,
    isCover,
  };
}

const countries = [
  {
    slug: "turkiye",
    name: "Turkey",
    description:
      "A country spanning Europe and Asia, known for its ancient history, vibrant cities, and Mediterranean coastline.",
    coverImageUrl: "https://picsum.photos/seed/turkiye-cover/1200/600",
    cities: [
      {
        slug: "istanbul",
        name: "Istanbul",
        description:
          "Turkey's largest city, straddling the Bosphorus strait between Europe and Asia, rich in Byzantine and Ottoman history.",
        coverImageUrl: "https://picsum.photos/seed/istanbul-cover/1200/600",
        latitude: 41.0082,
        longitude: 28.9784,
        places: [
          {
            slug: "hagia-sophia",
            name: "Hagia Sophia",
            category: Category.MONUMENT,
            description:
              "A former Byzantine cathedral and Ottoman mosque, now a museum-mosque, famed for its massive dome and mosaics.",
            address: "Sultan Ahmet, Ayasofya Meydanı No:1, Fatih/Istanbul",
            latitude: 41.0086,
            longitude: 28.9802,
            priceLevel: 2,
            website: "https://example.com/hagia-sophia",
            phone: "+90 212 522 1750",
            openingHours: { "mon-sun": "09:00-19:00" },
            photos: [
              photo("hagia-sophia", 1, "Exterior view of the dome", true),
              photo("hagia-sophia", 2, "Interior mosaics"),
            ],
          },
          {
            slug: "blue-mosque",
            name: "Sultan Ahmed Mosque (Blue Mosque)",
            category: Category.MONUMENT,
            description:
              "An active Ottoman-era mosque famous for its six minarets and hand-painted blue tilework.",
            address: "Sultan Ahmet, Atmeydanı Cd. No:7, Fatih/Istanbul",
            latitude: 41.0054,
            longitude: 28.9768,
            priceLevel: 1,
            website: "https://example.com/blue-mosque",
            phone: "+90 212 458 4468",
            openingHours: { "mon-sun": "08:30-18:00" },
            photos: [photo("blue-mosque", 1, "Courtyard and minarets", true)],
          },
          {
            slug: "topkapi-palace",
            name: "Topkapi Palace",
            category: Category.ATTRACTION,
            description:
              "The primary residence of Ottoman sultans for nearly 400 years, now a museum housing imperial treasures.",
            address: "Cankurtaran, 34122 Fatih/Istanbul",
            latitude: 41.0115,
            longitude: 28.9833,
            priceLevel: 2,
            website: "https://example.com/topkapi-palace",
            phone: "+90 212 512 0480",
            openingHours: { "wed-mon": "09:00-18:00" },
            photos: [
              photo("topkapi-palace", 1, "Imperial gate", true),
              photo("topkapi-palace", 2, "Palace gardens"),
            ],
          },
          {
            slug: "belgrad-forest",
            name: "Belgrad Forest",
            category: Category.NATURE,
            description:
              "A large forested area on the European side of Istanbul, popular for walking, cycling, and picnics.",
            address: "Bahçeköy, Sarıyer/Istanbul",
            latitude: 41.1859,
            longitude: 28.9975,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "06:00-22:30" },
            photos: [photo("belgrad-forest", 1, "Forest trail", true)],
          },
          {
            slug: "karakoy-lokantasi",
            name: "Karaköy Lokantası",
            category: Category.RESTAURANT,
            description:
              "A well-loved meyhane-style restaurant serving traditional Turkish mezes and seafood near the Bosphorus.",
            address: "Kemankeş Karamustafa Paşa, Karaköy, Istanbul",
            latitude: 41.0246,
            longitude: 28.9762,
            priceLevel: 3,
            website: "https://example.com/karakoy-lokantasi",
            phone: "+90 212 292 4455",
            openingHours: { "mon-sat": "12:00-00:00", sun: "closed" },
            photos: [photo("karakoy-lokantasi", 1, "Dining room", true)],
          },
        ],
      },
      {
        slug: "antalya",
        name: "Antalya",
        description:
          "A resort city on Turkey's Mediterranean coast, known for its old town, beaches, and nearby ancient ruins.",
        coverImageUrl: "https://picsum.photos/seed/antalya-cover/1200/600",
        latitude: 36.8969,
        longitude: 30.7133,
        places: [
          {
            slug: "duden-waterfalls",
            name: "Düden Waterfalls",
            category: Category.NATURE,
            description:
              "A set of waterfalls where the Düden River cascades into the Mediterranean Sea, popular for scenic boat tours.",
            address: "Karataş, Antalya",
            latitude: 36.8461,
            longitude: 30.7825,
            priceLevel: 1,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:00-20:00" },
            photos: [photo("duden-waterfalls", 1, "Waterfall cliff view", true)],
          },
          {
            slug: "antalya-old-town",
            name: "Antalya Old Town (Kaleiçi)",
            category: Category.ATTRACTION,
            description:
              "A historic quarter of narrow streets, Ottoman houses, and the old harbor within ancient city walls.",
            address: "Kaleiçi, Muratpaşa/Antalya",
            latitude: 36.8858,
            longitude: 30.7056,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("antalya-old-town", 1, "Old harbor", true)],
          },
          {
            slug: "aspendos-theatre",
            name: "Aspendos Ancient Theatre",
            category: Category.MONUMENT,
            description:
              "A remarkably well-preserved Roman theatre, still used today for concerts and performances.",
            address: "Serik, Antalya",
            latitude: 36.9354,
            longitude: 31.1696,
            priceLevel: 2,
            website: "https://example.com/aspendos-theatre",
            phone: "+90 242 893 5017",
            openingHours: { "mon-sun": "09:00-19:00" },
            photos: [photo("aspendos-theatre", 1, "Theatre seating and stage", true)],
          },
          {
            slug: "vanilla-lounge",
            name: "Vanilla Lounge Restaurant",
            category: Category.RESTAURANT,
            description:
              "A stylish restaurant in Kaleiçi serving Mediterranean cuisine on a candlelit terrace.",
            address: "Kaleiçi, Zeytin Çıkmazı, Antalya",
            latitude: 36.8846,
            longitude: 30.7043,
            priceLevel: 3,
            website: "https://example.com/vanilla-lounge",
            phone: "+90 242 247 6013",
            openingHours: { "mon-sun": "18:00-01:00" },
            photos: [photo("vanilla-lounge", 1, "Terrace seating", true)],
          },
          {
            slug: "rixos-downtown-antalya",
            name: "Rixos Downtown Antalya",
            category: Category.HOTEL,
            description:
              "A modern hotel in central Antalya with rooftop pool views over the old town and the sea.",
            address: "Şirinyalı, Antalya",
            latitude: 36.8783,
            longitude: 30.7208,
            priceLevel: 4,
            website: "https://example.com/rixos-downtown-antalya",
            phone: "+90 242 249 4949",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("rixos-downtown-antalya", 1, "Rooftop pool", true)],
          },
        ],
      },
      {
        slug: "nevsehir",
        name: "Nevşehir (Cappadocia)",
        description:
          "A region in central Anatolia famous for its surreal fairy-chimney rock formations, cave dwellings, and sunrise hot-air balloon rides.",
        coverImageUrl: "https://picsum.photos/seed/nevsehir-cover/1200/600",
        latitude: 38.6431,
        longitude: 34.7128,
        places: [
          {
            slug: "goreme-open-air-museum",
            name: "Göreme Open Air Museum",
            category: Category.MONUMENT,
            description:
              "A UNESCO World Heritage site of rock-cut Byzantine churches and monasteries carved into the volcanic landscape.",
            address: "Göreme, Nevşehir",
            latitude: 38.6431,
            longitude: 34.8287,
            priceLevel: 2,
            website: "https://example.com/goreme-open-air-museum",
            phone: "+90 384 271 2167",
            openingHours: { "mon-sun": "08:00-17:00" },
            photos: [photo("goreme-open-air-museum", 1, "Rock-cut church facades", true)],
          },
          {
            slug: "fairy-chimneys-pasabag",
            name: "Fairy Chimneys of Cappadocia (Paşabağı)",
            category: Category.NATURE,
            description:
              "A valley of tall, mushroom-shaped volcanic rock formations, best seen at sunrise from a hot-air balloon.",
            address: "Paşabağı, Nevşehir",
            latitude: 38.6892,
            longitude: 34.8983,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [
              photo("fairy-chimneys-pasabag", 1, "Fairy chimney rock formations", true),
              photo("fairy-chimneys-pasabag", 2, "Hot-air balloons at sunrise"),
            ],
          },
          {
            slug: "uchisar-castle",
            name: "Uçhisar Castle",
            category: Category.ATTRACTION,
            description:
              "The highest point in Cappadocia, a natural rock citadel riddled with carved rooms and tunnels, offering panoramic views.",
            address: "Uçhisar, Nevşehir",
            latitude: 38.6319,
            longitude: 34.8115,
            priceLevel: 1,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:00-20:00" },
            photos: [photo("uchisar-castle", 1, "Rock citadel view", true)],
          },
          {
            slug: "old-greek-house-restaurant",
            name: "Old Greek House Restaurant",
            category: Category.RESTAURANT,
            description:
              "A restaurant in a restored Greek mansion in Mustafapaşa, serving traditional Anatolian dishes and pottery kebabs.",
            address: "Mustafapaşa, Nevşehir",
            latitude: 38.5722,
            longitude: 34.9138,
            priceLevel: 2,
            website: "https://example.com/old-greek-house-restaurant",
            phone: "+90 384 353 5306",
            openingHours: { "mon-sun": "11:00-22:00" },
            photos: [photo("old-greek-house-restaurant", 1, "Courtyard dining", true)],
          },
          {
            slug: "museum-hotel-cappadocia",
            name: "Museum Hotel Cappadocia",
            category: Category.HOTEL,
            description:
              "A luxury cave hotel built into the rock of Uçhisar, furnished with antiques and offering valley views.",
            address: "Uçhisar, Nevşehir",
            latitude: 38.6326,
            longitude: 34.8107,
            priceLevel: 4,
            website: "https://example.com/museum-hotel-cappadocia",
            phone: "+90 384 219 2220",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("museum-hotel-cappadocia", 1, "Cave suite terrace", true)],
          },
        ],
      },
      {
        slug: "denizli",
        name: "Denizli (Pamukkale)",
        description:
          "A city in southwestern Turkey known for the white travertine terraces of Pamukkale and the ancient ruins of Hierapolis.",
        coverImageUrl: "https://picsum.photos/seed/denizli-cover/1200/600",
        latitude: 37.7765,
        longitude: 29.0864,
        places: [
          {
            slug: "pamukkale-travertines",
            name: "Pamukkale Travertines",
            category: Category.NATURE,
            description:
              "Cascading white mineral terraces formed by calcium-rich thermal springs, one of Turkey's most iconic natural sights.",
            address: "Pamukkale, Denizli",
            latitude: 37.9203,
            longitude: 29.1206,
            priceLevel: 2,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:00-19:00" },
            photos: [photo("pamukkale-travertines", 1, "White travertine terraces", true)],
          },
          {
            slug: "hierapolis-ancient-city",
            name: "Hierapolis Ancient City",
            category: Category.MONUMENT,
            description:
              "A well-preserved Greco-Roman spa city adjoining Pamukkale, with a Roman theatre and an extensive necropolis.",
            address: "Pamukkale, Denizli",
            latitude: 37.9256,
            longitude: 29.1233,
            priceLevel: 2,
            website: "https://example.com/hierapolis-ancient-city",
            phone: "+90 258 272 2077",
            openingHours: { "mon-sun": "08:00-19:00" },
            photos: [photo("hierapolis-ancient-city", 1, "Roman theatre ruins", true)],
          },
          {
            slug: "cleopatra-antique-pool",
            name: "Cleopatra Antique Pool",
            category: Category.ATTRACTION,
            description:
              "A thermal pool scattered with sunken Roman columns, said to have been a gift from Marc Antony to Cleopatra.",
            address: "Pamukkale, Denizli",
            latitude: 37.9239,
            longitude: 29.1223,
            priceLevel: 3,
            website: "https://example.com/cleopatra-antique-pool",
            phone: "+90 258 272 2024",
            openingHours: { "mon-sun": "08:00-19:00" },
            photos: [photo("cleopatra-antique-pool", 1, "Submerged columns", true)],
          },
          {
            slug: "colossae-restaurant",
            name: "Colossae Restaurant",
            category: Category.RESTAURANT,
            description:
              "A restaurant near the thermal springs serving Turkish and Aegean dishes with views of the travertines.",
            address: "Pamukkale, Denizli",
            latitude: 37.918,
            longitude: 29.119,
            priceLevel: 2,
            website: "https://example.com/colossae-restaurant",
            phone: "+90 258 272 2035",
            openingHours: { "mon-sun": "11:00-22:00" },
            photos: [photo("colossae-restaurant", 1, "Terrace dining", true)],
          },
          {
            slug: "doga-thermal-spa",
            name: "Doga Thermal Health & Spa",
            category: Category.HOTEL,
            description:
              "A thermal spa hotel near Pamukkale with mineral-fed pools and treatment rooms.",
            address: "Karahayıt, Denizli",
            latitude: 37.9482,
            longitude: 29.1103,
            priceLevel: 3,
            website: "https://example.com/doga-thermal-spa",
            phone: "+90 258 271 4118",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("doga-thermal-spa", 1, "Thermal pool", true)],
          },
        ],
      },
      {
        slug: "selcuk",
        name: "Selçuk (Ephesus)",
        description:
          "A small Aegean town best known as the gateway to the ancient city of Ephesus and the surrounding historic sites.",
        coverImageUrl: "https://picsum.photos/seed/selcuk-cover/1200/600",
        latitude: 37.9497,
        longitude: 27.3689,
        places: [
          {
            slug: "ephesus-ancient-city",
            name: "Ephesus Ancient City",
            category: Category.MONUMENT,
            description:
              "One of the best-preserved ancient cities in the Mediterranean, home to the Library of Celsus and the Great Theatre.",
            address: "Selçuk, İzmir",
            latitude: 37.9395,
            longitude: 27.3417,
            priceLevel: 2,
            website: "https://example.com/ephesus-ancient-city",
            phone: "+90 232 892 6402",
            openingHours: { "mon-sun": "08:00-18:30" },
            photos: [
              photo("ephesus-ancient-city", 1, "Library of Celsus facade", true),
              photo("ephesus-ancient-city", 2, "The Great Theatre"),
            ],
          },
          {
            slug: "house-of-virgin-mary",
            name: "House of the Virgin Mary",
            category: Category.ATTRACTION,
            description:
              "A small stone chapel on Mt. Koressos believed by many to be the final home of the Virgin Mary, an important pilgrimage site.",
            address: "Bülbüldağı, Selçuk",
            latitude: 37.9186,
            longitude: 27.3336,
            priceLevel: 1,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:00-18:00" },
            photos: [photo("house-of-virgin-mary", 1, "Stone chapel exterior", true)],
          },
          {
            slug: "sirince-village",
            name: "Şirince Village",
            category: Category.NATURE,
            description:
              "A hillside village of old Greek stone houses surrounded by vineyards and orchards, known for its fruit wines.",
            address: "Şirince, Selçuk",
            latitude: 37.9436,
            longitude: 27.4067,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("sirince-village", 1, "Hillside village houses", true)],
          },
          {
            slug: "selcuk-koftecisi",
            name: "Selçuk Köftecisi",
            category: Category.RESTAURANT,
            description:
              "A local favorite for grilled köfte and Aegean mezes near the Ephesus Museum.",
            address: "Selçuk, İzmir",
            latitude: 37.95,
            longitude: 27.3711,
            priceLevel: 1,
            website: "https://example.com/selcuk-koftecisi",
            phone: "+90 232 892 6696",
            openingHours: { "mon-sun": "11:00-22:00" },
            photos: [photo("selcuk-koftecisi", 1, "Grilled köfte plate", true)],
          },
          {
            slug: "hotel-bella-selcuk",
            name: "Hotel Bella",
            category: Category.HOTEL,
            description:
              "A family-run boutique hotel in central Selçuk, a short walk from the Ephesus Museum and train station.",
            address: "Selçuk, İzmir",
            latitude: 37.9505,
            longitude: 27.3702,
            priceLevel: 2,
            website: "https://example.com/hotel-bella-selcuk",
            phone: "+90 232 892 3944",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-bella-selcuk", 1, "Hotel courtyard", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "fransa",
    name: "France",
    description:
      "A Western European country known for its art, cuisine, and landmarks ranging from the Eiffel Tower to the French Riviera.",
    coverImageUrl: "https://picsum.photos/seed/fransa-cover/1200/600",
    cities: [
      {
        slug: "paris",
        name: "Paris",
        description:
          "France's capital, celebrated for its museums, architecture, and status as a global center of art and fashion.",
        coverImageUrl: "https://picsum.photos/seed/paris-cover/1200/600",
        latitude: 48.8566,
        longitude: 2.3522,
        places: [
          {
            slug: "eiffel-tower",
            name: "Eiffel Tower",
            category: Category.MONUMENT,
            description:
              "The iconic iron lattice tower on the Champ de Mars, one of the most recognizable structures in the world.",
            address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
            latitude: 48.8584,
            longitude: 2.2945,
            priceLevel: 3,
            website: "https://example.com/eiffel-tower",
            phone: "+33 892 70 12 39",
            openingHours: { "mon-sun": "09:00-23:45" },
            photos: [
              photo("eiffel-tower", 1, "View from the Trocadéro", true),
              photo("eiffel-tower", 2, "Tower at night"),
            ],
          },
          {
            slug: "louvre-museum",
            name: "Louvre Museum",
            category: Category.ATTRACTION,
            description:
              "The world's largest art museum, home to the Mona Lisa and thousands of other works across historic galleries.",
            address: "Rue de Rivoli, 75001 Paris",
            latitude: 48.8606,
            longitude: 2.3376,
            priceLevel: 3,
            website: "https://example.com/louvre-museum",
            phone: "+33 1 40 20 53 17",
            openingHours: { "wed-mon": "09:00-18:00", tue: "closed" },
            photos: [photo("louvre-museum", 1, "Glass pyramid entrance", true)],
          },
          {
            slug: "le-jules-verne",
            name: "Le Jules Verne",
            category: Category.RESTAURANT,
            description:
              "A fine-dining restaurant on the Eiffel Tower's second floor, offering panoramic views of Paris.",
            address: "Eiffel Tower, Avenue Gustave Eiffel, 75007 Paris",
            latitude: 48.8579,
            longitude: 2.2946,
            priceLevel: 4,
            website: "https://example.com/le-jules-verne",
            phone: "+33 1 45 55 61 44",
            openingHours: { "mon-sun": "12:00-13:30, 19:00-21:30" },
            photos: [photo("le-jules-verne", 1, "Dining room with a view", true)],
          },
          {
            slug: "bois-de-boulogne",
            name: "Bois de Boulogne",
            category: Category.NATURE,
            description:
              "A large public park on the western edge of Paris with lakes, gardens, and walking trails.",
            address: "Bois de Boulogne, 75016 Paris",
            latitude: 48.8637,
            longitude: 2.2497,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("bois-de-boulogne", 1, "Lakeside path", true)],
          },
          {
            slug: "hotel-ritz-paris",
            name: "Hôtel Ritz Paris",
            category: Category.HOTEL,
            description:
              "A legendary luxury hotel on Place Vendôme, known for its opulent rooms and storied history.",
            address: "15 Place Vendôme, 75001 Paris",
            latitude: 48.8683,
            longitude: 2.3286,
            priceLevel: 4,
            website: "https://example.com/hotel-ritz-paris",
            phone: "+33 1 43 16 30 30",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-ritz-paris", 1, "Hotel facade", true)],
          },
        ],
      },
      {
        slug: "nice",
        name: "Nice",
        description:
          "A city on the French Riviera known for its pebble beaches, Mediterranean climate, and historic old town.",
        coverImageUrl: "https://picsum.photos/seed/nice-cover/1200/600",
        latitude: 43.7102,
        longitude: 7.262,
        places: [
          {
            slug: "promenade-des-anglais",
            name: "Promenade des Anglais",
            category: Category.NATURE,
            description:
              "A famous seaside promenade along the Baie des Anges, popular for walking, cycling, and sea views.",
            address: "Promenade des Anglais, 06000 Nice",
            latitude: 43.6959,
            longitude: 7.2652,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("promenade-des-anglais", 1, "Seafront promenade", true)],
          },
          {
            slug: "castle-hill-nice",
            name: "Castle Hill (Colline du Château)",
            category: Category.ATTRACTION,
            description:
              "A hilltop park overlooking Nice and the Mediterranean, site of a former medieval citadel.",
            address: "Montée Lesage, 06300 Nice",
            latitude: 43.6959,
            longitude: 7.2833,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:30-20:00" },
            photos: [photo("castle-hill-nice", 1, "Viewpoint over the bay", true)],
          },
          {
            slug: "cathedrale-sainte-reparate",
            name: "Cathédrale Sainte-Réparate",
            category: Category.MONUMENT,
            description:
              "A 17th-century baroque cathedral in the heart of Old Nice, dedicated to the city's patron saint.",
            address: "3 Place Rossetti, 06300 Nice",
            latitude: 43.6968,
            longitude: 7.2777,
            priceLevel: 1,
            website: "https://example.com/cathedrale-sainte-reparate",
            phone: "+33 4 93 62 34 40",
            openingHours: { "mon-sun": "09:00-18:00" },
            photos: [photo("cathedrale-sainte-reparate", 1, "Baroque facade", true)],
          },
          {
            slug: "la-petite-maison",
            name: "La Petite Maison",
            category: Category.RESTAURANT,
            description:
              "A celebrated Niçoise restaurant serving regional Provençal dishes in a warm, bistro-style setting.",
            address: "11 Rue Saint-François de Paule, 06300 Nice",
            latitude: 43.6955,
            longitude: 7.2733,
            priceLevel: 4,
            website: "https://example.com/la-petite-maison",
            phone: "+33 4 93 92 59 59",
            openingHours: { "mon-sat": "12:00-14:30, 19:30-22:30", sun: "closed" },
            photos: [photo("la-petite-maison", 1, "Bistro interior", true)],
          },
          {
            slug: "hotel-negresco",
            name: "Hôtel Negresco",
            category: Category.HOTEL,
            description:
              "A landmark Belle Époque hotel on the Promenade des Anglais, recognizable by its distinctive pink dome.",
            address: "37 Promenade des Anglais, 06000 Nice",
            latitude: 43.695,
            longitude: 7.2611,
            priceLevel: 4,
            website: "https://example.com/hotel-negresco",
            phone: "+33 4 93 16 64 00",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-negresco", 1, "Pink dome facade", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "italya",
    name: "Italy",
    description:
      "A southern European country famed for its Renaissance art, ancient ruins, and regional cuisine, from Rome to Venice and Florence.",
    coverImageUrl: "https://picsum.photos/seed/italya-cover/1200/600",
    cities: [
      {
        slug: "roma",
        name: "Rome",
        description:
          "Italy's capital, home to over two millennia of history, from the ruins of the Roman Forum to Renaissance and Baroque landmarks.",
        coverImageUrl: "https://picsum.photos/seed/roma-cover/1200/600",
        latitude: 41.9028,
        longitude: 12.4964,
        places: [
          {
            slug: "colosseum",
            name: "Colosseum",
            category: Category.MONUMENT,
            description:
              "The largest ancient amphitheatre ever built, once host to gladiatorial contests, and Rome's most recognizable landmark.",
            address: "Piazza del Colosseo, 1, 00184 Roma RM",
            latitude: 41.8902,
            longitude: 12.4922,
            priceLevel: 2,
            website: "https://example.com/colosseum",
            phone: "+39 06 3996 7700",
            openingHours: { "mon-sun": "08:30-19:00" },
            photos: [
              photo("colosseum", 1, "Exterior arches", true),
              photo("colosseum", 2, "Interior arena view"),
            ],
          },
          {
            slug: "vatican-museums",
            name: "Vatican Museums",
            category: Category.ATTRACTION,
            description:
              "A vast museum complex within Vatican City housing the Sistine Chapel and centuries of papal art collections.",
            address: "Viale Vaticano, 00165 Roma RM",
            latitude: 41.9065,
            longitude: 12.4536,
            priceLevel: 3,
            website: "https://example.com/vatican-museums",
            phone: "+39 06 6988 4676",
            openingHours: { "mon-sat": "08:00-19:00", sun: "closed" },
            photos: [photo("vatican-museums", 1, "Museum gallery hall", true)],
          },
          {
            slug: "villa-borghese-gardens",
            name: "Villa Borghese Gardens",
            category: Category.NATURE,
            description:
              "A large landscaped park in central Rome with gardens, a lake, and the Galleria Borghese art museum.",
            address: "Piazzale Napoleone I, 00197 Roma RM",
            latitude: 41.9109,
            longitude: 12.4823,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "06:30-20:00" },
            photos: [photo("villa-borghese-gardens", 1, "Park gardens and lake", true)],
          },
          {
            slug: "roscioli",
            name: "Roscioli",
            category: Category.RESTAURANT,
            description:
              "A beloved deli and restaurant near Campo de' Fiori serving classic Roman pasta dishes and cured meats.",
            address: "Via dei Giubbonari, 21, 00186 Roma RM",
            latitude: 41.8955,
            longitude: 12.4733,
            priceLevel: 3,
            website: "https://example.com/roscioli",
            phone: "+39 06 687 5287",
            openingHours: { "mon-sun": "12:30-16:00, 19:00-00:00" },
            photos: [photo("roscioli", 1, "Deli counter and dining room", true)],
          },
          {
            slug: "hotel-eden-rome",
            name: "Hotel Eden",
            category: Category.HOTEL,
            description:
              "A five-star hotel near the Spanish Steps with a rooftop restaurant overlooking the rooftops of Rome.",
            address: "Via Ludovisi, 49, 00187 Roma RM",
            latitude: 41.9066,
            longitude: 12.4879,
            priceLevel: 4,
            website: "https://example.com/hotel-eden-rome",
            phone: "+39 06 478 121",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-eden-rome", 1, "Rooftop terrace view", true)],
          },
        ],
      },
      {
        slug: "venedik",
        name: "Venice",
        description:
          "A city built on a lagoon of canals and islands, celebrated for St. Mark's Square, gondolas, and centuries of maritime history.",
        coverImageUrl: "https://picsum.photos/seed/venedik-cover/1200/600",
        latitude: 45.4408,
        longitude: 12.3155,
        places: [
          {
            slug: "st-marks-basilica",
            name: "St. Mark's Basilica",
            category: Category.MONUMENT,
            description:
              "A Byzantine-style cathedral on St. Mark's Square, decorated with gold mosaics spanning eight centuries.",
            address: "Piazza San Marco, 328, 30124 Venezia VE",
            latitude: 45.4345,
            longitude: 12.3397,
            priceLevel: 1,
            website: "https://example.com/st-marks-basilica",
            phone: "+39 041 270 8311",
            openingHours: { "mon-sun": "09:30-17:15" },
            photos: [photo("st-marks-basilica", 1, "Golden mosaic facade", true)],
          },
          {
            slug: "doges-palace",
            name: "Doge's Palace",
            category: Category.ATTRACTION,
            description:
              "The former residence of the Doge of Venice, a Gothic palace connected to the old prisons by the Bridge of Sighs.",
            address: "Piazza San Marco, 1, 30124 Venezia VE",
            latitude: 45.4337,
            longitude: 12.3403,
            priceLevel: 3,
            website: "https://example.com/doges-palace",
            phone: "+39 041 271 5911",
            openingHours: { "mon-sun": "09:00-18:00" },
            photos: [photo("doges-palace", 1, "Gothic palace facade", true)],
          },
          {
            slug: "lido-di-venezia",
            name: "Lido di Venezia",
            category: Category.NATURE,
            description:
              "A narrow barrier island facing the Adriatic, with sandy beaches a short vaporetto ride from central Venice.",
            address: "Lido di Venezia, Venezia VE",
            latitude: 45.4085,
            longitude: 12.3667,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("lido-di-venezia", 1, "Sandy beach shoreline", true)],
          },
          {
            slug: "osteria-alle-testiere",
            name: "Osteria alle Testiere",
            category: Category.RESTAURANT,
            description:
              "A tiny, highly regarded seafood restaurant near the Rialto, known for fresh catch and a short daily menu.",
            address: "Calle del Mondo Novo, 5801, 30122 Venezia VE",
            latitude: 45.4368,
            longitude: 12.3419,
            priceLevel: 4,
            website: "https://example.com/osteria-alle-testiere",
            phone: "+39 041 522 7220",
            openingHours: { "tue-sat": "19:00-22:00", "sun-mon": "closed" },
            photos: [photo("osteria-alle-testiere", 1, "Small dining room", true)],
          },
          {
            slug: "hotel-danieli",
            name: "Hotel Danieli",
            category: Category.HOTEL,
            description:
              "A historic luxury hotel in a converted Gothic palace, steps from St. Mark's Square with lagoon views.",
            address: "Riva degli Schiavoni, 4196, 30122 Venezia VE",
            latitude: 45.4342,
            longitude: 12.3417,
            priceLevel: 4,
            website: "https://example.com/hotel-danieli",
            phone: "+39 041 522 6480",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-danieli", 1, "Lagoon-view facade", true)],
          },
        ],
      },
      {
        slug: "floransa",
        name: "Florence",
        description:
          "The birthplace of the Renaissance, filled with world-class art, historic churches, and views over the Tuscan hills.",
        coverImageUrl: "https://picsum.photos/seed/floransa-cover/1200/600",
        latitude: 43.7696,
        longitude: 11.2558,
        places: [
          {
            slug: "florence-cathedral",
            name: "Florence Cathedral (Duomo)",
            category: Category.MONUMENT,
            description:
              "A Gothic cathedral crowned by Brunelleschi's iconic red-tiled dome, dominating the Florence skyline.",
            address: "Piazza del Duomo, 50122 Firenze FI",
            latitude: 43.7731,
            longitude: 11.256,
            priceLevel: 2,
            website: "https://example.com/florence-cathedral",
            phone: "+39 055 230 2885",
            openingHours: { "mon-sat": "10:15-16:30", sun: "13:30-16:45" },
            photos: [photo("florence-cathedral", 1, "Dome and bell tower", true)],
          },
          {
            slug: "uffizi-gallery",
            name: "Uffizi Gallery",
            category: Category.ATTRACTION,
            description:
              "One of the world's great art museums, home to masterpieces by Botticelli, Michelangelo, and Leonardo da Vinci.",
            address: "Piazzale degli Uffizi, 6, 50122 Firenze FI",
            latitude: 43.7687,
            longitude: 11.256,
            priceLevel: 3,
            website: "https://example.com/uffizi-gallery",
            phone: "+39 055 238 8651",
            openingHours: { "tue-sun": "08:15-18:30", mon: "closed" },
            photos: [photo("uffizi-gallery", 1, "Gallery corridor", true)],
          },
          {
            slug: "boboli-gardens",
            name: "Boboli Gardens",
            category: Category.NATURE,
            description:
              "Formal Renaissance gardens behind the Pitti Palace, with sculpture-lined avenues and views over Florence.",
            address: "Piazza de' Pitti, 1, 50125 Firenze FI",
            latitude: 43.7649,
            longitude: 11.25,
            priceLevel: 2,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:15-18:30" },
            photos: [photo("boboli-gardens", 1, "Garden terraces", true)],
          },
          {
            slug: "trattoria-mario",
            name: "Trattoria Mario",
            category: Category.RESTAURANT,
            description:
              "A no-frills, always-busy trattoria near the Mercato Centrale serving hearty Tuscan classics at shared tables.",
            address: "Via Rosina, 2, 50123 Firenze FI",
            latitude: 43.7757,
            longitude: 11.2537,
            priceLevel: 2,
            website: null,
            phone: "+39 055 218 550",
            openingHours: { "mon-sat": "12:00-15:30", sun: "closed" },
            photos: [photo("trattoria-mario", 1, "Communal dining tables", true)],
          },
          {
            slug: "hotel-brunelleschi",
            name: "Hotel Brunelleschi",
            category: Category.HOTEL,
            description:
              "A boutique hotel built around a Byzantine tower, a short walk from the Duomo, with a small museum in the basement.",
            address: "Piazza Santa Elisabetta, 3, 50122 Firenze FI",
            latitude: 43.7714,
            longitude: 11.2559,
            priceLevel: 4,
            website: "https://example.com/hotel-brunelleschi",
            phone: "+39 055 27370",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-brunelleschi", 1, "Historic tower facade", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "japonya",
    name: "Japan",
    description:
      "An island nation blending ultramodern cities with centuries-old temples, shrines, and traditional gardens.",
    coverImageUrl: "https://picsum.photos/seed/japonya-cover/1200/600",
    cities: [
      {
        slug: "tokyo",
        name: "Tokyo",
        description:
          "Japan's capital, a dense metropolis mixing neon-lit districts, historic temples, and serene urban green spaces.",
        coverImageUrl: "https://picsum.photos/seed/tokyo-cover/1200/600",
        latitude: 35.6762,
        longitude: 139.6503,
        places: [
          {
            slug: "sensoji-temple",
            name: "Senso-ji Temple",
            category: Category.MONUMENT,
            description:
              "Tokyo's oldest Buddhist temple, approached through the Kaminarimon gate and a market street of traditional shops.",
            address: "2 Chome-3-1 Asakusa, Taito City, Tokyo",
            latitude: 35.7148,
            longitude: 139.7967,
            priceLevel: null,
            website: "https://example.com/sensoji-temple",
            phone: "+81 3-3842-0181",
            openingHours: { "mon-sun": "06:00-17:00" },
            photos: [photo("sensoji-temple", 1, "Kaminarimon gate", true)],
          },
          {
            slug: "tokyo-tower",
            name: "Tokyo Tower",
            category: Category.ATTRACTION,
            description:
              "A red-and-white communications tower inspired by the Eiffel Tower, with observation decks over the city.",
            address: "4 Chome-2-8 Shibakoen, Minato City, Tokyo",
            latitude: 35.6586,
            longitude: 139.7454,
            priceLevel: 2,
            website: "https://example.com/tokyo-tower",
            phone: "+81 3-3433-5111",
            openingHours: { "mon-sun": "09:00-23:00" },
            photos: [photo("tokyo-tower", 1, "Tower against the skyline", true)],
          },
          {
            slug: "meiji-shrine-forest",
            name: "Meiji Shrine Forest",
            category: Category.NATURE,
            description:
              "A dense forested shrine precinct in the middle of the city, planted with trees donated from across Japan.",
            address: "1-1 Yoyogikamizonocho, Shibuya City, Tokyo",
            latitude: 35.6764,
            longitude: 139.6993,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "05:00-18:00" },
            photos: [photo("meiji-shrine-forest", 1, "Forested shrine path", true)],
          },
          {
            slug: "sukiyabashi-jiro",
            name: "Sukiyabashi Jiro",
            category: Category.RESTAURANT,
            description:
              "A world-renowned, ten-seat sushi restaurant in a Ginza subway station, made famous by a documentary film.",
            address: "4 Chome-2-15 Ginza, Chuo City, Tokyo",
            latitude: 35.672,
            longitude: 139.7639,
            priceLevel: 4,
            website: "https://example.com/sukiyabashi-jiro",
            phone: "+81 3-3535-3600",
            openingHours: { "mon-sat": "11:30-14:00", sun: "closed" },
            photos: [photo("sukiyabashi-jiro", 1, "Sushi counter", true)],
          },
          {
            slug: "park-hyatt-tokyo",
            name: "Park Hyatt Tokyo",
            category: Category.HOTEL,
            description:
              "A luxury hotel occupying the top floors of a Shinjuku skyscraper, familiar from the film Lost in Translation.",
            address: "3 Chome-7-1-2 Nishishinjuku, Shinjuku City, Tokyo",
            latitude: 35.6853,
            longitude: 139.6905,
            priceLevel: 4,
            website: "https://example.com/park-hyatt-tokyo",
            phone: "+81 3-5322-1234",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("park-hyatt-tokyo", 1, "Skyline view suite", true)],
          },
        ],
      },
      {
        slug: "kyoto",
        name: "Kyoto",
        description:
          "Japan's former imperial capital, known for thousands of temples and shrines, geisha districts, and traditional gardens.",
        coverImageUrl: "https://picsum.photos/seed/kyoto-cover/1200/600",
        latitude: 35.0116,
        longitude: 135.7681,
        places: [
          {
            slug: "fushimi-inari-taisha",
            name: "Fushimi Inari Taisha",
            category: Category.MONUMENT,
            description:
              "A Shinto shrine famous for thousands of vermilion torii gates winding up the forested slopes of Mount Inari.",
            address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
            latitude: 34.9671,
            longitude: 135.7727,
            priceLevel: null,
            website: "https://example.com/fushimi-inari-taisha",
            phone: "+81 75-641-7331",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("fushimi-inari-taisha", 1, "Torii gate tunnel", true)],
          },
          {
            slug: "kinkakuji",
            name: "Kinkaku-ji (Golden Pavilion)",
            category: Category.ATTRACTION,
            description:
              "A Zen Buddhist temple whose top two floors are covered in gold leaf, reflected in the surrounding pond.",
            address: "1 Kinkakujicho, Kita Ward, Kyoto",
            latitude: 35.0394,
            longitude: 135.7292,
            priceLevel: 1,
            website: "https://example.com/kinkakuji",
            phone: "+81 75-461-0013",
            openingHours: { "mon-sun": "09:00-17:00" },
            photos: [photo("kinkakuji", 1, "Golden pavilion over the pond", true)],
          },
          {
            slug: "arashiyama-bamboo-grove",
            name: "Arashiyama Bamboo Grove",
            category: Category.NATURE,
            description:
              "A towering bamboo forest path on Kyoto's western edge, one of the most photographed natural sights in Japan.",
            address: "Sagaogurayama Tabuchiyamacho, Ukyo Ward, Kyoto",
            latitude: 35.017,
            longitude: 135.672,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("arashiyama-bamboo-grove", 1, "Bamboo grove path", true)],
          },
          {
            slug: "gion-karyo",
            name: "Gion Karyo",
            category: Category.RESTAURANT,
            description:
              "A kaiseki restaurant in the historic Gion district, serving seasonal multi-course Japanese fine dining.",
            address: "Gion, Higashiyama Ward, Kyoto",
            latitude: 35.0037,
            longitude: 135.7752,
            priceLevel: 4,
            website: "https://example.com/gion-karyo",
            phone: "+81 75-541-2733",
            openingHours: { "mon-sun": "17:00-22:00" },
            photos: [photo("gion-karyo", 1, "Kaiseki course presentation", true)],
          },
          {
            slug: "ritz-carlton-kyoto",
            name: "The Ritz-Carlton Kyoto",
            category: Category.HOTEL,
            description:
              "A riverside luxury hotel near Kyoto's historic center, blending traditional Japanese design with modern comfort.",
            address: "Kamogawa Nijo-Ohashi Hotori, Nakagyo Ward, Kyoto",
            latitude: 35.0106,
            longitude: 135.7702,
            priceLevel: 4,
            website: "https://example.com/ritz-carlton-kyoto",
            phone: "+81 75-746-5555",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("ritz-carlton-kyoto", 1, "Riverside hotel exterior", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "ispanya",
    name: "Spain",
    description:
      "An Iberian country known for Moorish architecture, Gaudí's landmarks, and vibrant regional food and festival culture.",
    coverImageUrl: "https://picsum.photos/seed/ispanya-cover/1200/600",
    cities: [
      {
        slug: "sevilla",
        name: "Seville",
        description:
          "The capital of Andalusia, known for its Moorish palaces, flamenco tradition, and one of the largest cathedrals in the world.",
        coverImageUrl: "https://picsum.photos/seed/sevilla-cover/1200/600",
        latitude: 37.3891,
        longitude: -5.9845,
        places: [
          {
            slug: "seville-cathedral",
            name: "Seville Cathedral",
            category: Category.MONUMENT,
            description:
              "The largest Gothic cathedral in the world, built on the site of a mosque and home to Christopher Columbus's tomb.",
            address: "Av. de la Constitución, s/n, 41004 Sevilla",
            latitude: 37.3859,
            longitude: -5.9926,
            priceLevel: 2,
            website: "https://example.com/seville-cathedral",
            phone: "+34 954 21 49 71",
            openingHours: { "mon-sat": "10:00-18:00", sun: "14:30-18:00" },
            photos: [photo("seville-cathedral", 1, "Gothic cathedral nave", true)],
          },
          {
            slug: "alcazar-of-seville",
            name: "Alcázar of Seville",
            category: Category.ATTRACTION,
            description:
              "A royal palace of intricate Mudéjar architecture, still used by the Spanish royal family, with elaborate gardens.",
            address: "Patio de Banderas, s/n, 41004 Sevilla",
            latitude: 37.3833,
            longitude: -5.9903,
            priceLevel: 3,
            website: "https://example.com/alcazar-of-seville",
            phone: "+34 954 78 75 00",
            openingHours: { "mon-sun": "09:30-19:00" },
            photos: [photo("alcazar-of-seville", 1, "Mudéjar palace courtyard", true)],
          },
          {
            slug: "parque-de-maria-luisa",
            name: "Parque de María Luisa",
            category: Category.NATURE,
            description:
              "A shaded public park of fountains, tiled plazas, and pavilions, home to the semicircular Plaza de España.",
            address: "Paseo de las Delicias, s/n, 41013 Sevilla",
            latitude: 37.3746,
            longitude: -5.9873,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "08:00-22:00" },
            photos: [photo("parque-de-maria-luisa", 1, "Plaza de España view", true)],
          },
          {
            slug: "restaurante-az-zait",
            name: "Restaurante Az-Zait",
            category: Category.RESTAURANT,
            description:
              "A family-run restaurant near the cathedral serving traditional Andalusian and Sevillian dishes.",
            address: "Plaza Ponce de León, 10, 41003 Sevilla",
            latitude: 37.3894,
            longitude: -5.995,
            priceLevel: 2,
            website: "https://example.com/restaurante-az-zait",
            phone: "+34 954 90 64 75",
            openingHours: { "mon-sat": "13:00-16:00, 20:00-23:30", sun: "closed" },
            photos: [photo("restaurante-az-zait", 1, "Dining room", true)],
          },
          {
            slug: "hotel-alfonso-xiii",
            name: "Hotel Alfonso XIII",
            category: Category.HOTEL,
            description:
              "A grand historic hotel built in Andalusian revival style for the 1929 Ibero-American Exposition.",
            address: "San Fernando, 2, 41004 Sevilla",
            latitude: 37.3821,
            longitude: -5.9917,
            priceLevel: 4,
            website: "https://example.com/hotel-alfonso-xiii",
            phone: "+34 954 91 70 00",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-alfonso-xiii", 1, "Courtyard facade", true)],
          },
        ],
      },
      {
        slug: "barselona",
        name: "Barcelona",
        description:
          "A Mediterranean city famous for Antoni Gaudí's architecture, Gothic quarter streets, and beachfront promenades.",
        coverImageUrl: "https://picsum.photos/seed/barselona-cover/1200/600",
        latitude: 41.3874,
        longitude: 2.1686,
        places: [
          {
            slug: "sagrada-familia",
            name: "Sagrada Família",
            category: Category.MONUMENT,
            description:
              "Antoni Gaudí's unfinished basilica, a Barcelona icon known for its soaring towers and intricate facades.",
            address: "Carrer de Mallorca, 401, 08013 Barcelona",
            latitude: 41.4036,
            longitude: 2.1744,
            priceLevel: 3,
            website: "https://example.com/sagrada-familia",
            phone: "+34 932 08 04 14",
            openingHours: { "mon-sun": "09:00-18:00" },
            photos: [
              photo("sagrada-familia", 1, "Basilica towers", true),
              photo("sagrada-familia", 2, "Interior stained glass"),
            ],
          },
          {
            slug: "park-guell",
            name: "Park Güell",
            category: Category.NATURE,
            description:
              "A public park designed by Gaudí with mosaic-covered terraces, sculptures, and views over the city to the sea.",
            address: "Carrer d'Olot, s/n, 08024 Barcelona",
            latitude: 41.4145,
            longitude: 2.1527,
            priceLevel: 2,
            website: "https://example.com/park-guell",
            phone: "+34 934 09 18 31",
            openingHours: { "mon-sun": "09:30-19:30" },
            photos: [photo("park-guell", 1, "Mosaic terrace overlook", true)],
          },
          {
            slug: "gothic-quarter",
            name: "Gothic Quarter",
            category: Category.ATTRACTION,
            description:
              "Barcelona's old town, a maze of medieval streets around the Barcelona Cathedral and Plaça Reial.",
            address: "Barri Gòtic, 08002 Barcelona",
            latitude: 41.3833,
            longitude: 2.1765,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("gothic-quarter", 1, "Medieval street", true)],
          },
          {
            slug: "tickets-bar",
            name: "Tickets Bar",
            category: Category.RESTAURANT,
            description:
              "A playful, Michelin-starred tapas bar by the Adrià brothers, known for inventive small plates.",
            address: "Av. del Paral·lel, 164, 08015 Barcelona",
            latitude: 41.3745,
            longitude: 2.1489,
            priceLevel: 4,
            website: "https://example.com/tickets-bar",
            phone: "+34 932 92 42 53",
            openingHours: { "tue-sat": "19:00-22:30", "sun-mon": "closed" },
            photos: [photo("tickets-bar", 1, "Tapas bar counter", true)],
          },
          {
            slug: "hotel-arts-barcelona",
            name: "Hotel Arts Barcelona",
            category: Category.HOTEL,
            description:
              "A beachfront skyscraper hotel near Port Olímpic, with sweeping views over the Mediterranean and the city.",
            address: "Carrer de la Marina, 19-21, 08005 Barcelona",
            latitude: 41.3857,
            longitude: 2.1967,
            priceLevel: 4,
            website: "https://example.com/hotel-arts-barcelona",
            phone: "+34 932 21 10 00",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-arts-barcelona", 1, "Beachfront tower", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "abd",
    name: "United States",
    description:
      "A large North American country of diverse landscapes and cities, from the monuments of Washington to the skyline of New York.",
    coverImageUrl: "https://picsum.photos/seed/abd-cover/1200/600",
    cities: [
      {
        slug: "new-york",
        name: "New York",
        description:
          "The most populous city in the United States, known for its skyline, museums, and cultural landmarks across five boroughs.",
        coverImageUrl: "https://picsum.photos/seed/new-york-cover/1200/600",
        latitude: 40.7128,
        longitude: -74.006,
        places: [
          {
            slug: "statue-of-liberty",
            name: "Statue of Liberty",
            category: Category.MONUMENT,
            description:
              "A colossal neoclassical sculpture on Liberty Island, a global symbol of freedom given by France in 1886.",
            address: "Liberty Island, New York, NY 10004",
            latitude: 40.6892,
            longitude: -74.0445,
            priceLevel: 2,
            website: "https://example.com/statue-of-liberty",
            phone: "+1 212-363-3200",
            openingHours: { "mon-sun": "09:00-17:00" },
            photos: [photo("statue-of-liberty", 1, "Statue from the harbor", true)],
          },
          {
            slug: "central-park",
            name: "Central Park",
            category: Category.NATURE,
            description:
              "An 843-acre park in the middle of Manhattan, with lakes, meadows, and paths used by millions of visitors each year.",
            address: "New York, NY 10024",
            latitude: 40.7829,
            longitude: -73.9654,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "06:00-01:00" },
            photos: [photo("central-park", 1, "Park path in autumn", true)],
          },
          {
            slug: "metropolitan-museum-of-art",
            name: "Metropolitan Museum of Art",
            category: Category.ATTRACTION,
            description:
              "One of the world's largest art museums, with a collection spanning 5,000 years across two million square feet.",
            address: "1000 5th Ave, New York, NY 10028",
            latitude: 40.7794,
            longitude: -73.9632,
            priceLevel: 2,
            website: "https://example.com/metropolitan-museum-of-art",
            phone: "+1 212-535-7710",
            openingHours: { "mon-sun": "10:00-17:00" },
            photos: [photo("metropolitan-museum-of-art", 1, "Museum grand staircase", true)],
          },
          {
            slug: "katzs-delicatessen",
            name: "Katz's Delicatessen",
            category: Category.RESTAURANT,
            description:
              "A landmark Lower East Side deli open since 1888, famous for hand-carved pastrami sandwiches.",
            address: "205 E Houston St, New York, NY 10002",
            latitude: 40.7223,
            longitude: -73.9874,
            priceLevel: 2,
            website: "https://example.com/katzs-delicatessen",
            phone: "+1 212-254-2246",
            openingHours: { "mon-sun": "08:00-22:00" },
            photos: [photo("katzs-delicatessen", 1, "Deli counter", true)],
          },
          {
            slug: "the-plaza-hotel",
            name: "The Plaza Hotel",
            category: Category.HOTEL,
            description:
              "A historic luxury hotel at the corner of Central Park, a New York landmark since 1907.",
            address: "768 5th Ave, New York, NY 10019",
            latitude: 40.7644,
            longitude: -73.9744,
            priceLevel: 4,
            website: "https://example.com/the-plaza-hotel",
            phone: "+1 212-759-3000",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("the-plaza-hotel", 1, "Fifth Avenue entrance", true)],
          },
        ],
      },
      {
        slug: "washington",
        name: "Washington",
        description:
          "The capital of the United States, home to the nation's monuments, the Capitol, and the Smithsonian museums.",
        coverImageUrl: "https://picsum.photos/seed/washington-cover/1200/600",
        latitude: 38.9072,
        longitude: -77.0369,
        places: [
          {
            slug: "lincoln-memorial",
            name: "Lincoln Memorial",
            category: Category.MONUMENT,
            description:
              "A neoclassical memorial honoring Abraham Lincoln, overlooking the Reflecting Pool at the western end of the National Mall.",
            address: "2 Lincoln Memorial Cir NW, Washington, DC 20037",
            latitude: 38.8893,
            longitude: -77.0502,
            priceLevel: null,
            website: "https://example.com/lincoln-memorial",
            phone: "+1 202-426-6841",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("lincoln-memorial", 1, "Memorial statue interior", true)],
          },
          {
            slug: "smithsonian-air-and-space-museum",
            name: "Smithsonian National Air and Space Museum",
            category: Category.ATTRACTION,
            description:
              "A free museum housing historic aircraft and spacecraft, including the Wright Flyer and Apollo 11 command module.",
            address: "655 Jefferson Dr SW, Washington, DC 20560",
            latitude: 38.8882,
            longitude: -77.0199,
            priceLevel: null,
            website: "https://example.com/smithsonian-air-and-space-museum",
            phone: "+1 202-633-2214",
            openingHours: { "mon-sun": "10:00-17:30" },
            photos: [photo("smithsonian-air-and-space-museum", 1, "Aircraft exhibit hall", true)],
          },
          {
            slug: "national-mall",
            name: "National Mall",
            category: Category.NATURE,
            description:
              "A large open green space stretching between the Capitol and the Lincoln Memorial, lined with monuments and museums.",
            address: "National Mall, Washington, DC 20565",
            latitude: 38.8895,
            longitude: -77.0353,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("national-mall", 1, "Mall lawn and monuments", true)],
          },
          {
            slug: "old-ebbitt-grill",
            name: "Old Ebbitt Grill",
            category: Category.RESTAURANT,
            description:
              "Washington's oldest saloon-style restaurant, a block from the White House, known for its raw bar and classic American fare.",
            address: "675 15th St NW, Washington, DC 20005",
            latitude: 38.8977,
            longitude: -77.0365,
            priceLevel: 3,
            website: "https://example.com/old-ebbitt-grill",
            phone: "+1 202-347-4801",
            openingHours: { "mon-sun": "07:30-01:00" },
            photos: [photo("old-ebbitt-grill", 1, "Historic saloon interior", true)],
          },
          {
            slug: "the-hay-adams",
            name: "The Hay-Adams",
            category: Category.HOTEL,
            description:
              "A historic hotel across Lafayette Square from the White House, known for its rooftop views and classic decor.",
            address: "800 16th St NW, Washington, DC 20006",
            latitude: 38.9004,
            longitude: -77.0374,
            priceLevel: 4,
            website: "https://example.com/the-hay-adams",
            phone: "+1 202-638-6600",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("the-hay-adams", 1, "Hotel facade", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "brezilya",
    name: "Brazil",
    description:
      "South America's largest country, known for its beaches, mountains, and the cultural energy of Rio de Janeiro and São Paulo.",
    coverImageUrl: "https://picsum.photos/seed/brezilya-cover/1200/600",
    cities: [
      {
        slug: "rio-de-janeiro",
        name: "Rio de Janeiro",
        description:
          "A coastal city framed by mountains and beaches, home to Christ the Redeemer and the Carnival celebration.",
        coverImageUrl: "https://picsum.photos/seed/rio-de-janeiro-cover/1200/600",
        latitude: -22.9068,
        longitude: -43.1729,
        places: [
          {
            slug: "christ-the-redeemer",
            name: "Christ the Redeemer",
            category: Category.MONUMENT,
            description:
              "An Art Deco statue of Jesus Christ atop Corcovado mountain, one of the New Seven Wonders of the World.",
            address: "Parque Nacional da Tijuca, Rio de Janeiro",
            latitude: -22.9519,
            longitude: -43.2105,
            priceLevel: 2,
            website: "https://example.com/christ-the-redeemer",
            phone: "+55 21 2558-1329",
            openingHours: { "mon-sun": "08:00-19:00" },
            photos: [photo("christ-the-redeemer", 1, "Statue over the city", true)],
          },
          {
            slug: "copacabana-beach",
            name: "Copacabana Beach",
            category: Category.NATURE,
            description:
              "A famous 4-kilometer stretch of sandy beach along Rio's coastline, framed by a wave-patterned promenade.",
            address: "Copacabana, Rio de Janeiro",
            latitude: -22.9711,
            longitude: -43.1822,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("copacabana-beach", 1, "Beach and promenade", true)],
          },
          {
            slug: "sugarloaf-mountain",
            name: "Sugarloaf Mountain",
            category: Category.ATTRACTION,
            description:
              "A granite peak reached by cable car, offering panoramic views over Guanabara Bay and the city.",
            address: "Av. Pasteur, 520, Urca, Rio de Janeiro",
            latitude: -22.9492,
            longitude: -43.1545,
            priceLevel: 3,
            website: "https://example.com/sugarloaf-mountain",
            phone: "+55 21 2546-8400",
            openingHours: { "mon-sun": "08:00-19:50" },
            photos: [photo("sugarloaf-mountain", 1, "Cable car and bay view", true)],
          },
          {
            slug: "confeitaria-colombo",
            name: "Confeitaria Colombo",
            category: Category.RESTAURANT,
            description:
              "A grand Belle Époque café in downtown Rio, serving Brazilian pastries under stained-glass skylights since 1894.",
            address: "R. Gonçalves Dias, 32, Centro, Rio de Janeiro",
            latitude: -22.9035,
            longitude: -43.177,
            priceLevel: 2,
            website: "https://example.com/confeitaria-colombo",
            phone: "+55 21 2505-1500",
            openingHours: { "mon-sat": "09:00-19:00", sun: "09:00-14:00" },
            photos: [photo("confeitaria-colombo", 1, "Belle Époque interior", true)],
          },
          {
            slug: "copacabana-palace",
            name: "Copacabana Palace",
            category: Category.HOTEL,
            description:
              "An iconic beachfront hotel on Copacabana Beach, hosting celebrities and dignitaries since 1923.",
            address: "Av. Atlântica, 1702, Copacabana, Rio de Janeiro",
            latitude: -22.9664,
            longitude: -43.1789,
            priceLevel: 4,
            website: "https://example.com/copacabana-palace",
            phone: "+55 21 2548-7070",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("copacabana-palace", 1, "Beachfront facade", true)],
          },
        ],
      },
      {
        slug: "sao-paulo",
        name: "São Paulo",
        description:
          "Brazil's largest city and financial center, known for its museums, diverse food scene, and sprawling skyline.",
        coverImageUrl: "https://picsum.photos/seed/sao-paulo-cover/1200/600",
        latitude: -23.5505,
        longitude: -46.6333,
        places: [
          {
            slug: "catedral-da-se",
            name: "São Paulo Cathedral (Catedral da Sé)",
            category: Category.MONUMENT,
            description:
              "A Neo-Gothic cathedral in the historic center of São Paulo, with capacity for 8,000 worshippers.",
            address: "Praça da Sé, São Paulo",
            latitude: -23.5505,
            longitude: -46.6333,
            priceLevel: null,
            website: null,
            phone: "+55 11 3107-6832",
            openingHours: { "mon-sun": "08:00-19:00" },
            photos: [photo("catedral-da-se", 1, "Cathedral facade", true)],
          },
          {
            slug: "ibirapuera-park",
            name: "Ibirapuera Park",
            category: Category.NATURE,
            description:
              "São Paulo's largest urban park, with lakes, running paths, and several of the city's modernist museums.",
            address: "Av. Pedro Álvares Cabral, São Paulo",
            latitude: -23.5874,
            longitude: -46.6576,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "05:00-00:00" },
            photos: [photo("ibirapuera-park", 1, "Park lake view", true)],
          },
          {
            slug: "masp",
            name: "Museu de Arte de São Paulo (MASP)",
            category: Category.ATTRACTION,
            description:
              "An art museum famous for its red concrete-and-glass building suspended above a public plaza on Avenida Paulista.",
            address: "Av. Paulista, 1578, São Paulo",
            latitude: -23.5614,
            longitude: -46.6559,
            priceLevel: 2,
            website: "https://example.com/masp",
            phone: "+55 11 3149-5959",
            openingHours: { "tue-sun": "10:00-18:00", mon: "closed" },
            photos: [photo("masp", 1, "Suspended museum building", true)],
          },
          {
            slug: "dom-restaurant",
            name: "D.O.M.",
            category: Category.RESTAURANT,
            description:
              "A fine-dining restaurant celebrated for reinventing Brazilian ingredients, among Latin America's best-known kitchens.",
            address: "R. Barão de Capanema, 549, São Paulo",
            latitude: -23.5616,
            longitude: -46.669,
            priceLevel: 4,
            website: "https://example.com/dom-restaurant",
            phone: "+55 11 3088-0761",
            openingHours: { "tue-sat": "19:30-23:00", "sun-mon": "closed" },
            photos: [photo("dom-restaurant", 1, "Tasting menu plating", true)],
          },
          {
            slug: "hotel-unique",
            name: "Hotel Unique",
            category: Category.HOTEL,
            description:
              "A striking slice-shaped hotel on Avenida Brasil, known for its rooftop bar with skyline views.",
            address: "Av. Brig. Luís Antônio, 4700, São Paulo",
            latitude: -23.5772,
            longitude: -46.66,
            priceLevel: 4,
            website: "https://example.com/hotel-unique",
            phone: "+55 11 3055-4700",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-unique", 1, "Rooftop bar view", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "ingiltere",
    name: "United Kingdom",
    description:
      "An island nation in Northwestern Europe, home to centuries of royal history, world-class museums, and the capital, London.",
    coverImageUrl: "https://picsum.photos/seed/ingiltere-cover/1200/600",
    cities: [
      {
        slug: "londra",
        name: "London",
        description:
          "The UK's capital, a global city of royal palaces, historic museums, and diverse neighborhoods along the Thames.",
        coverImageUrl: "https://picsum.photos/seed/londra-cover/1200/600",
        latitude: 51.5072,
        longitude: -0.1276,
        places: [
          {
            slug: "big-ben",
            name: "Big Ben",
            category: Category.MONUMENT,
            description:
              "The nickname for the Great Bell of the clock at the north end of the Houses of Parliament, a London icon.",
            address: "Westminster, London SW1A 0AA",
            latitude: 51.5007,
            longitude: -0.1246,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("big-ben", 1, "Clock tower over Westminster Bridge", true)],
          },
          {
            slug: "hyde-park",
            name: "Hyde Park",
            category: Category.NATURE,
            description:
              "One of London's largest royal parks, with the Serpentine lake, Speakers' Corner, and open green lawns.",
            address: "Hyde Park, London W2 2UH",
            latitude: 51.5073,
            longitude: -0.1657,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "05:00-00:00" },
            photos: [photo("hyde-park", 1, "Serpentine lake", true)],
          },
          {
            slug: "british-museum",
            name: "British Museum",
            category: Category.ATTRACTION,
            description:
              "A free museum of human history and culture, home to the Rosetta Stone and the Elgin Marbles.",
            address: "Great Russell St, London WC1B 3DG",
            latitude: 51.5194,
            longitude: -0.127,
            priceLevel: null,
            website: "https://example.com/british-museum",
            phone: "+44 20 7323 8299",
            openingHours: { "mon-sun": "10:00-17:00" },
            photos: [photo("british-museum", 1, "Great Court glass roof", true)],
          },
          {
            slug: "dishoom",
            name: "Dishoom",
            category: Category.RESTAURANT,
            description:
              "A popular Bombay café-style restaurant chain, with its original Covent Garden branch known for long queues.",
            address: "12 Upper St Martin's Ln, London WC2H 9FB",
            latitude: 51.5117,
            longitude: -0.1246,
            priceLevel: 2,
            website: "https://example.com/dishoom",
            phone: "+44 20 7420 9320",
            openingHours: { "mon-sun": "08:00-23:00" },
            photos: [photo("dishoom", 1, "Café dining room", true)],
          },
          {
            slug: "the-savoy",
            name: "The Savoy",
            category: Category.HOTEL,
            description:
              "A historic five-star hotel on the Strand overlooking the Thames, open since 1889 and famed for its Art Deco style.",
            address: "Strand, London WC2R 0EZ",
            latitude: 51.5101,
            longitude: -0.1201,
            priceLevel: 4,
            website: "https://example.com/the-savoy",
            phone: "+44 20 7836 4343",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("the-savoy", 1, "Art Deco entrance", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "fas",
    name: "Morocco",
    description:
      "A North African kingdom known for its imperial cities, markets, and the blend of Arab, Berber, and French influences.",
    coverImageUrl: "https://picsum.photos/seed/fas-cover/1200/600",
    cities: [
      {
        slug: "marakes",
        name: "Marrakech",
        description:
          "A former imperial city known for its walled medina, bustling souks, and gardens at the foot of the Atlas Mountains.",
        coverImageUrl: "https://picsum.photos/seed/marakes-cover/1200/600",
        latitude: 31.6295,
        longitude: -7.9811,
        places: [
          {
            slug: "koutoubia-mosque",
            name: "Koutoubia Mosque",
            category: Category.MONUMENT,
            description:
              "Marrakech's largest mosque, its 12th-century minaret serving as a landmark visible across the city.",
            address: "Avenue Mohammed V, Marrakech",
            latitude: 31.6238,
            longitude: -7.9936,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("koutoubia-mosque", 1, "Minaret at dusk", true)],
          },
          {
            slug: "jardin-majorelle",
            name: "Jardin Majorelle",
            category: Category.NATURE,
            description:
              "A vivid cobalt-blue garden of cacti and exotic plants, once owned by fashion designer Yves Saint Laurent.",
            address: "Rue Yves St Laurent, Marrakech",
            latitude: 31.6412,
            longitude: -8.0031,
            priceLevel: 2,
            website: "https://example.com/jardin-majorelle",
            phone: "+212 5243-31830",
            openingHours: { "mon-sun": "08:00-17:30" },
            photos: [photo("jardin-majorelle", 1, "Cobalt-blue garden pavilion", true)],
          },
          {
            slug: "jemaa-el-fnaa",
            name: "Jemaa el-Fnaa",
            category: Category.ATTRACTION,
            description:
              "The main square of the Marrakech medina, filled by day with vendors and by night with food stalls and performers.",
            address: "Jemaa el-Fnaa, Marrakech",
            latitude: 31.6258,
            longitude: -7.9891,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("jemaa-el-fnaa", 1, "Square at night", true)],
          },
          {
            slug: "nomad-restaurant",
            name: "Nomad Restaurant",
            category: Category.RESTAURANT,
            description:
              "A modern Moroccan restaurant with a rooftop terrace overlooking the spice souk in the medina.",
            address: "1 Derb Aarjan, Rahba Lakdima, Marrakech",
            latitude: 31.627,
            longitude: -7.9886,
            priceLevel: 3,
            website: "https://example.com/nomad-restaurant",
            phone: "+212 5243-81609",
            openingHours: { "mon-sun": "12:00-23:00" },
            photos: [photo("nomad-restaurant", 1, "Rooftop terrace dining", true)],
          },
          {
            slug: "la-mamounia",
            name: "La Mamounia",
            category: Category.HOTEL,
            description:
              "A legendary luxury hotel set in historic gardens near the medina walls, a Marrakech landmark since 1923.",
            address: "Avenue Bab Jdid, Marrakech",
            latitude: 31.6193,
            longitude: -7.9955,
            priceLevel: 4,
            website: "https://example.com/la-mamounia",
            phone: "+212 5243-88600",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("la-mamounia", 1, "Garden and hotel facade", true)],
          },
        ],
      },
    ],
  },
  {
    slug: "yunanistan",
    name: "Greece",
    description:
      "A southeastern European country regarded as the cradle of Western civilization, known for ancient ruins and island life.",
    coverImageUrl: "https://picsum.photos/seed/yunanistan-cover/1200/600",
    cities: [
      {
        slug: "atina",
        name: "Athens",
        description:
          "Greece's capital, one of the world's oldest cities, dominated by the ancient Acropolis and its surrounding ruins.",
        coverImageUrl: "https://picsum.photos/seed/atina-cover/1200/600",
        latitude: 37.9838,
        longitude: 23.7275,
        places: [
          {
            slug: "acropolis-of-athens",
            name: "Acropolis of Athens",
            category: Category.MONUMENT,
            description:
              "An ancient citadel on a rocky outcrop above Athens, crowned by the Parthenon temple to Athena.",
            address: "Athens 105 58",
            latitude: 37.9715,
            longitude: 23.7267,
            priceLevel: 2,
            website: "https://example.com/acropolis-of-athens",
            phone: "+30 210 321 4172",
            openingHours: { "mon-sun": "08:00-20:00" },
            photos: [
              photo("acropolis-of-athens", 1, "The Parthenon", true),
              photo("acropolis-of-athens", 2, "View over Athens"),
            ],
          },
          {
            slug: "national-garden-of-athens",
            name: "National Garden of Athens",
            category: Category.NATURE,
            description:
              "A shaded public garden behind the Greek Parliament, with duck ponds, ancient ruins, and a small zoo.",
            address: "Vasilissis Amalias, Athens 105 57",
            latitude: 37.9738,
            longitude: 23.7367,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "06:00-20:00" },
            photos: [photo("national-garden-of-athens", 1, "Shaded garden path", true)],
          },
          {
            slug: "plaka-district",
            name: "Plaka District",
            category: Category.ATTRACTION,
            description:
              "The oldest neighborhood of Athens, a maze of narrow streets and neoclassical houses beneath the Acropolis.",
            address: "Plaka, Athens 105 56",
            latitude: 37.9722,
            longitude: 23.7285,
            priceLevel: null,
            website: null,
            phone: null,
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("plaka-district", 1, "Narrow street beneath the Acropolis", true)],
          },
          {
            slug: "karamanlidika-tou-fani",
            name: "Karamanlidika tou Fani",
            category: Category.RESTAURANT,
            description:
              "A deli-restaurant in the Athens Central Market serving cured meats and mezes rooted in Asia Minor Greek cuisine.",
            address: "Sokratous 1, Athens 105 52",
            latitude: 37.9765,
            longitude: 23.7256,
            priceLevel: 2,
            website: "https://example.com/karamanlidika-tou-fani",
            phone: "+30 210 325 4184",
            openingHours: { "mon-sat": "10:00-18:00", sun: "closed" },
            photos: [photo("karamanlidika-tou-fani", 1, "Deli counter and tables", true)],
          },
          {
            slug: "hotel-grande-bretagne",
            name: "Hotel Grande Bretagne",
            category: Category.HOTEL,
            description:
              "A grand historic hotel on Syntagma Square, host to dignitaries since 1874, with rooftop views of the Acropolis.",
            address: "1 Vasileos Georgiou A, Athens 105 64",
            latitude: 37.9755,
            longitude: 23.7348,
            priceLevel: 4,
            website: "https://example.com/hotel-grande-bretagne",
            phone: "+30 210 333 0000",
            openingHours: { "mon-sun": "00:00-23:59" },
            photos: [photo("hotel-grande-bretagne", 1, "Rooftop view of the Acropolis", true)],
          },
        ],
      },
    ],
  },
];

const demoUsers = [
  { email: "ayse.yilmaz@example.com", name: "Ayşe Yılmaz" },
  { email: "john.smith@example.com", name: "John Smith" },
  { email: "marie.dubois@example.com", name: "Marie Dubois" },
];

const sampleReviews: Record<
  string,
  { userEmail: string; rating: number; title: string; body: string }[]
> = {
  "hagia-sophia": [
    {
      userEmail: "john.smith@example.com",
      rating: 5,
      title: "Breathtaking",
      body: "The scale of the dome and the history in every corner make this a must-see.",
    },
    {
      userEmail: "marie.dubois@example.com",
      rating: 4,
      title: "Very crowded but worth it",
      body: "Go early in the morning to avoid the lines.",
    },
  ],
  "blue-mosque": [
    {
      userEmail: "ayse.yilmaz@example.com",
      rating: 5,
      title: "Stunning tilework",
      body: "One of the most beautiful mosques I have visited.",
    },
  ],
  "duden-waterfalls": [
    {
      userEmail: "john.smith@example.com",
      rating: 4,
      title: "Great boat tour",
      body: "Seeing the waterfall drop straight into the sea was unforgettable.",
    },
  ],
  "eiffel-tower": [
    {
      userEmail: "ayse.yilmaz@example.com",
      rating: 5,
      title: "Classic for a reason",
      body: "The view from the top at sunset is unbeatable.",
    },
    {
      userEmail: "marie.dubois@example.com",
      rating: 3,
      title: "Overpriced but iconic",
      body: "Worth doing once, book tickets online to skip the queue.",
    },
  ],
  "louvre-museum": [
    {
      userEmail: "john.smith@example.com",
      rating: 5,
      title: "Could spend days here",
      body: "Way too much to see in one visit, plan accordingly.",
    },
  ],
  "la-petite-maison": [
    {
      userEmail: "marie.dubois@example.com",
      rating: 5,
      title: "Best meal in Nice",
      body: "The vegetable dishes and the service were excellent.",
    },
  ],
  "hotel-negresco": [
    {
      userEmail: "john.smith@example.com",
      rating: 4,
      title: "Beautiful and historic",
      body: "Rooms are a bit dated but the character makes up for it.",
    },
  ],
};

async function main() {
  const users = new Map<string, string>();
  for (const u of demoUsers) {
    const user = await prisma.user.upsert({
      where: { email: u.email },
      update: { name: u.name },
      create: { email: u.email, name: u.name },
    });
    users.set(u.email, user.id);
  }

  const placeIds: string[] = [];

  for (const country of countries) {
    const { cities, ...countryData } = country;
    const dbCountry = await prisma.country.upsert({
      where: { slug: country.slug },
      update: countryData,
      create: countryData,
    });

    for (const city of cities) {
      const { places, ...cityData } = city;
      const dbCity = await prisma.city.upsert({
        where: { slug: city.slug },
        update: { ...cityData, countryId: dbCountry.id },
        create: { ...cityData, countryId: dbCountry.id },
      });

      for (const place of places) {
        const { photos, ...placeData } = place;
        const dbPlace = await prisma.place.upsert({
          where: { slug: place.slug },
          update: { ...placeData, cityId: dbCity.id },
          create: { ...placeData, cityId: dbCity.id },
        });
        placeIds.push(dbPlace.id);

        for (const p of photos) {
          await prisma.photo.upsert({
            where: { id: `${dbPlace.id}-${p.url}` },
            update: p,
            create: { ...p, id: `${dbPlace.id}-${p.url}`, placeId: dbPlace.id },
          });
        }

        const reviews = sampleReviews[place.slug] ?? [];
        for (const r of reviews) {
          const userId = users.get(r.userEmail);
          if (!userId) continue;
          await prisma.review.upsert({
            where: { placeId_userId: { placeId: dbPlace.id, userId } },
            update: { rating: r.rating, title: r.title, body: r.body },
            create: {
              placeId: dbPlace.id,
              userId,
              rating: r.rating,
              title: r.title,
              body: r.body,
            },
          });
        }

        if (reviews.length > 0) {
          const agg = await prisma.review.aggregate({
            where: { placeId: dbPlace.id },
            _avg: { rating: true },
            _count: true,
          });
          await prisma.place.update({
            where: { id: dbPlace.id },
            data: {
              avgRating: agg._avg.rating ?? 0,
              reviewCount: agg._count,
            },
          });
        }
      }
    }
  }

  console.log(
    `Seeded ${countries.length} countries, ${countries.reduce((n, c) => n + c.cities.length, 0)} cities, ${placeIds.length} places, ${demoUsers.length} users.`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
